name: Lint & Format (NestJS)

on:
  push:
    branches:
      - '**'
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.yml'
      - '**.yaml'
      - '**.md'
      - '!dist/**'
      - '!coverage/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.yml'
      - '**.yaml'
      - '**.md'
      - '!dist/**'
      - '!coverage/**'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  # ---- PRs: check only (no commits) ----
  check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: ESLint (check)
        run: yarn lint

      - name: Prettier (check)
        run: yarn format:check

  fix-and-format:
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for committing)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: ESLint (auto-fix)
        run: yarn lint

      - name: Prettier (write)
        run: yarn format

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(ci): auto-format & lint fixes [skip ci]'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          file_pattern: |
            **/*.ts
            **/*.js
            **/*.json
            **/*.yml
            **/*.yaml
            **/*.md

      - name: ESLint (verify)
        run: yarn lint
      - name: Prettier (verify)
        run: yarn format:check
